#!/bin/bash

[[ $# -lt 1 ]] && echo -e "usage: please specify which user. ex:\n       ./preprocess.sh username" && exit 1 || echo "username: $1"

# switch to user
su $1 -c "bash $MYE_SCRIPTS_DIR/user_go" 

